# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Hipótese da Criatividade Industrial
#email: your-email@domain.com
lang: pt
description: >
  Hipótese da Criatividade Industrial é aplicação de engenharia memética focada em uso de criatividade onde um indivíduo, através de sua interação com indústria, seja capaz de causar impacto positivo em sua comunidade, independente de governo.
baseurl: "/criatividade-industrial" # the subpath of your site, e.g. /blog
url: "https://fititnt.github.io" # url completa para o site. NÃO termine com barra
twitter_username: fititnt
github_username:  fititnt/criatividade-industrial
github_repository: fititnt/criatividade-industrial

permalink: /:categories/:slug.html

# Usado por jekyll-seo-tag
author: "Emerson Rocha"
#  twitter: webiwg

# Build settings
markdown: kramdown
theme: minima

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
